# Generated by Django 4.0 on 2021-12-24 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car_table',
            fields=[
                ('engine_number', models.IntegerField(primary_key=True, serialize=False)),
                ('model', models.CharField(max_length=50)),
                ('manufacture_year', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer_table',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Insurance_Agent_table',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer_table')),
            ],
        ),
        migrations.CreateModel(
            name='Notification_table',
            fields=[
                ('policy_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='main.customer_table')),
                ('date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Policy_table',
            fields=[
                ('policy_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('status', models.BooleanField(default=True)),
                ('type', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('agent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.insurance_agent_table')),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer_table')),
                ('engine_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.car_table')),
            ],
        ),
        migrations.AddField(
            model_name='car_table',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customer_table'),
        ),
    ]
